-- MySQL Script generated by MySQL Workbench
-- Fri Jul 28 16:44:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema artido
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema artido
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `artido` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema dados
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema estudo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estudo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estudo` DEFAULT CHARACTER SET utf8mb3 ;
-- -----------------------------------------------------
-- Schema treinamento
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema treinamento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `treinamento` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `artido` ;

-- -----------------------------------------------------
-- Table `artido`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artido`.`evento` (
  `CodEvento` VARCHAR(4) NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `Sigla` VARCHAR(10) NOT NULL,
  `Ano` YEAR NULL DEFAULT NULL,
  PRIMARY KEY (`CodEvento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artido`.`artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artido`.`artigo` (
  `CodArtigo` VARCHAR(4) NOT NULL,
  `Titulo` VARCHAR(80) NOT NULL,
  `Nota` DECIMAL(4,2) NOT NULL,
  `Idioma` VARCHAR(15) NULL DEFAULT NULL,
  `CodEvento` VARCHAR(4) NULL DEFAULT NULL,
  PRIMARY KEY (`CodArtigo`),
  INDEX `CodEvento_idx` (`CodEvento` ASC) VISIBLE,
  CONSTRAINT `CodEvento`
    FOREIGN KEY (`CodEvento`)
    REFERENCES `artido`.`evento` (`CodEvento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `estudo`.`tabela pesquisador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`tabela pesquisador` (
  `idCodPesquisador` VARCHAR(4) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `instituicao` VARCHAR(40) NOT NULL,
  `nascimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idCodPesquisador`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `nascimento_UNIQUE` (`nascimento` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `artido`.`evento1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artido`.`evento1` (
  `CodEvento` VARCHAR(4) NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `Sigla` VARCHAR(10) NOT NULL,
  `Ano` YEAR NULL DEFAULT NULL,
  `tabela pesquisador_idCodPesquisador` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`CodEvento`, `tabela pesquisador_idCodPesquisador`),
  INDEX `fk_evento1_tabela pesquisador1_idx` (`tabela pesquisador_idCodPesquisador` ASC) VISIBLE,
  CONSTRAINT `fk_evento1_tabela pesquisador1`
    FOREIGN KEY (`tabela pesquisador_idCodPesquisador`)
    REFERENCES `estudo`.`tabela pesquisador` (`idCodPesquisador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `treinamento`.`final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treinamento`.`final` (
  `idfinal` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idfinal`),
  UNIQUE INDEX `idfinal_UNIQUE` (`idfinal` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artido`.`evento4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artido`.`evento4` (
  `CodEvento` VARCHAR(4) NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `Sigla` VARCHAR(10) NOT NULL,
  `Ano` YEAR NULL DEFAULT NULL,
  `final_idfinal` INT NOT NULL,
  PRIMARY KEY (`CodEvento`, `final_idfinal`),
  INDEX `fk_evento4_final1_idx` (`final_idfinal` ASC) VISIBLE,
  CONSTRAINT `fk_evento4_final1`
    FOREIGN KEY (`final_idfinal`)
    REFERENCES `treinamento`.`final` (`idfinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artido`.`pesquisador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artido`.`pesquisador` (
  `CodPesquisador` VARCHAR(4) NOT NULL,
  `Nome` VARCHAR(80) NOT NULL,
  `Instituicao` VARCHAR(40) NOT NULL,
  `Nascimento` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`CodPesquisador`),
  UNIQUE INDEX `Nome` (`Nome` ASC, `Nascimento` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artido`.`evento4_has_artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artido`.`evento4_has_artigo` (
  `evento4_CodEvento` VARCHAR(4) NOT NULL,
  `artigo_CodArtigo` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`evento4_CodEvento`, `artigo_CodArtigo`),
  INDEX `fk_evento4_has_artigo_artigo1_idx` (`artigo_CodArtigo` ASC) VISIBLE,
  INDEX `fk_evento4_has_artigo_evento41_idx` (`evento4_CodEvento` ASC) VISIBLE,
  CONSTRAINT `fk_evento4_has_artigo_evento41`
    FOREIGN KEY (`evento4_CodEvento`)
    REFERENCES `artido`.`evento4` (`CodEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento4_has_artigo_artigo1`
    FOREIGN KEY (`artigo_CodArtigo`)
    REFERENCES `artido`.`artigo` (`CodArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `artido`.`evento1_has_final`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `artido`.`evento1_has_final` (
  `evento1_CodEvento` VARCHAR(4) NOT NULL,
  `evento1_tabela pesquisador_idCodPesquisador` VARCHAR(4) NOT NULL,
  `final_idfinal` INT NOT NULL,
  PRIMARY KEY (`evento1_CodEvento`, `evento1_tabela pesquisador_idCodPesquisador`, `final_idfinal`),
  INDEX `fk_evento1_has_final_final1_idx` (`final_idfinal` ASC) VISIBLE,
  INDEX `fk_evento1_has_final_evento11_idx` (`evento1_CodEvento` ASC, `evento1_tabela pesquisador_idCodPesquisador` ASC) VISIBLE,
  CONSTRAINT `fk_evento1_has_final_evento11`
    FOREIGN KEY (`evento1_CodEvento` , `evento1_tabela pesquisador_idCodPesquisador`)
    REFERENCES `artido`.`evento1` (`CodEvento` , `tabela pesquisador_idCodPesquisador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento1_has_final_final1`
    FOREIGN KEY (`final_idfinal`)
    REFERENCES `treinamento`.`final` (`idfinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `estudo` ;

-- -----------------------------------------------------
-- Table `estudo`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`evento` (
  `idCodEvento` VARCHAR(4) NOT NULL,
  `nome do evento` VARCHAR(80) NOT NULL,
  `sigla` VARCHAR(10) NOT NULL,
  `ano` YEAR NOT NULL,
  PRIMARY KEY (`idCodEvento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `estudo`.`pesquisador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`pesquisador` (
  `idCodPesquisador` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `CodPesquisador` VARCHAR(4) NOT NULL,
  `Name` VARCHAR(80) NOT NULL,
  `Instituicao` VARCHAR(40) NOT NULL,
  `nascimento` DATE NOT NULL,
  `final_idfinal` INT NOT NULL,
  PRIMARY KEY (`idCodPesquisador`, `final_idfinal`),
  UNIQUE INDEX `idCodPesquisador_UNIQUE` (`idCodPesquisador` ASC) VISIBLE,
  UNIQUE INDEX `nascimento_UNIQUE` (`nascimento` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `fk_pesquisador_final_idx` (`final_idfinal` ASC) VISIBLE,
  CONSTRAINT `fk_pesquisador_final`
    FOREIGN KEY (`final_idfinal`)
    REFERENCES `treinamento`.`final` (`idfinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `estudo`.`pesquisador_has_artigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estudo`.`pesquisador_has_artigo` (
  `pesquisador_idCodPesquisador` INT UNSIGNED NOT NULL,
  `pesquisador_final_idfinal` INT NOT NULL,
  `artigo_CodArtigo` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`pesquisador_idCodPesquisador`, `pesquisador_final_idfinal`, `artigo_CodArtigo`),
  INDEX `fk_pesquisador_has_artigo_artigo1_idx` (`artigo_CodArtigo` ASC) VISIBLE,
  INDEX `fk_pesquisador_has_artigo_pesquisador1_idx` (`pesquisador_idCodPesquisador` ASC, `pesquisador_final_idfinal` ASC) VISIBLE,
  CONSTRAINT `fk_pesquisador_has_artigo_pesquisador1`
    FOREIGN KEY (`pesquisador_idCodPesquisador` , `pesquisador_final_idfinal`)
    REFERENCES `estudo`.`pesquisador` (`idCodPesquisador` , `final_idfinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pesquisador_has_artigo_artigo1`
    FOREIGN KEY (`artigo_CodArtigo`)
    REFERENCES `artido`.`artigo` (`CodArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;

USE `treinamento` ;

-- -----------------------------------------------------
-- Table `treinamento`.`fun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treinamento`.`fun` (
  `idfun` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome do funcionario` VARCHAR(80) NOT NULL,
  `sala` CHAR(10) NOT NULL DEFAULT 'sim',
  `solicitação` VARCHAR(100) NOT NULL,
  `pesquisador_CodPesquisador` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`idfun`),
  UNIQUE INDEX `idfun_UNIQUE` (`idfun` ASC) VISIBLE,
  UNIQUE INDEX `nome do funcionario_UNIQUE` (`nome do funcionario` ASC) VISIBLE,
  UNIQUE INDEX `sala_UNIQUE` (`sala` ASC) VISIBLE,
  INDEX `fk_fun_pesquisador1_idx` (`pesquisador_CodPesquisador` ASC) VISIBLE,
  CONSTRAINT `fk_fun_pesquisador1`
    FOREIGN KEY (`pesquisador_CodPesquisador`)
    REFERENCES `artido`.`pesquisador` (`CodPesquisador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `treinamento`.`func2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treinamento`.`func2` (
  `idfunc2` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idfunc2col` VARCHAR(10) NOT NULL,
  `fun_idfun` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idfunc2`, `idfunc2col`),
  UNIQUE INDEX `idfunc2_UNIQUE` (`idfunc2` ASC) VISIBLE,
  UNIQUE INDEX `idfunc2col_UNIQUE` (`idfunc2col` ASC) VISIBLE,
  INDEX `fk_func2_fun_idx` (`fun_idfun` ASC) VISIBLE,
  CONSTRAINT `fk_func2_fun`
    FOREIGN KEY (`fun_idfun`)
    REFERENCES `treinamento`.`fun` (`idfun`),
  CONSTRAINT `idfunc2`
    FOREIGN KEY (`fun_idfun`)
    REFERENCES `treinamento`.`fun` (`idfun`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `treinamento`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `treinamento`.`funcionario` (
  `codigo` VARCHAR(4) NOT NULL,
  `nome` VARCHAR(80) NOT NULL,
  `contrato` CHAR(3) NOT NULL DEFAULT 'SIM',
  `evento4_has_artigo_evento4_CodEvento` VARCHAR(4) NOT NULL,
  `evento4_has_artigo_artigo_CodArtigo` VARCHAR(4) NOT NULL,
  `final_idfinal` INT NOT NULL,
  `pesquisador_idCodPesquisador` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`codigo`, `pesquisador_idCodPesquisador`),
  INDEX `nome_idx` (`nome` ASC) VISIBLE,
  INDEX `fk_funcionario_evento4_has_artigo1_idx` (`evento4_has_artigo_evento4_CodEvento` ASC, `evento4_has_artigo_artigo_CodArtigo` ASC) VISIBLE,
  INDEX `fk_funcionario_final1_idx` (`final_idfinal` ASC) VISIBLE,
  INDEX `fk_funcionario_pesquisador1_idx` (`pesquisador_idCodPesquisador` ASC) VISIBLE,
  CONSTRAINT `nome`
    FOREIGN KEY (`nome`)
    REFERENCES `treinamento`.`func2` (`idfunc2col`),
  CONSTRAINT `fk_funcionario_evento4_has_artigo1`
    FOREIGN KEY (`evento4_has_artigo_evento4_CodEvento` , `evento4_has_artigo_artigo_CodArtigo`)
    REFERENCES `artido`.`evento4_has_artigo` (`evento4_CodEvento` , `artigo_CodArtigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_final1`
    FOREIGN KEY (`final_idfinal`)
    REFERENCES `treinamento`.`final` (`idfinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_pesquisador1`
    FOREIGN KEY (`pesquisador_idCodPesquisador`)
    REFERENCES `estudo`.`pesquisador` (`idCodPesquisador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
